In [23]:
import numpy as np

In [4]:
dizi=np.full((4,3),5)# 4 tane satır 3 sutun her birinde 5 olacak
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [7]:
dizi=np.array(["elma","erik","armut"])# string olarak gosterir


In [8]:
dizi

array(['elma', 'erik', 'armut'], dtype='<U5')

In [20]:
dizi=np.array([1,2,3,4])


array([1, 2, 3, 4])

In [ ]:
dizi=np.array([1,2,3.14])# tek boyutlu dizi

In [21]:
dizi.dtype

dtype('int32')

In [28]:
dizi=np.array([1,2,3,4.23],dtype=int)
dizi #tek boyutlu dizi turu int

array([1, 2, 3, 4])

In [27]:
birboyut=np.array([1,2,3,4]) # tek oyutlu dizi

#iki boyutlu dizi
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [29]:
birboyut

array([1, 2, 3, 4])

In [30]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
np.zeros(7)# 7 sıfırdan oluşan tek boyutlu dizi

array([0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((2,3),dtype=int)#*sıfırdan oluşan 2 boyutlu int dizi oluşturur

array([[0, 0, 0],
       [0, 0, 0]])

In [33]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.full((4,3),5)# 5 sayısından oluşan 2*3 lük dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [36]:
# başlangıç ve bitiş değerine gore dizi oluşturur

array([ 2,  7, 12, 17])

In [41]:
np.linspace(2,10,num=10)# başlangıç ve bitiş değeri arasında belirtilir

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [42]:
np.random.randint(0,10,5) # 0-10 aralığında rastgele 5 sayıda oluşan bir boyuıt dizi

array([1, 4, 6, 8, 5])

In [44]:
np.random.randint(0,10,(5,2))# 0-10 aralığında 5*2 rastgele sayıdan oluşan 2 boyutlu dizi 

array([[4, 4],
       [4, 4],
       [2, 8],
       [4, 8],
       [6, 3]])

In [46]:
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape  #dizideki eleman sayısını ogrenmek için 

(3, 4)

In [47]:
dizi.ndim #dizi boyutu

2

In [48]:
dizi.size #size dizideki toplam eleman sayısını gosteerir

12

In [49]:
dizi.itemsize #dizideki her bir elemanın bayt cinsinden değer verir

4

In [54]:
dizi=np.random.randint(0,10,(5,7))# 5 satır 7 sütun oluşsan rastgele sayılardan oluşan int türünde dizi
dizi

array([[6, 0, 3, 1, 5, 9, 9],
       [9, 0, 8, 6, 1, 8, 8],
       [3, 8, 3, 8, 0, 1, 9],
       [0, 4, 8, 0, 6, 3, 5],
       [3, 2, 5, 7, 5, 6, 8]])