In [1]:

import numpy as np #adı değştirir

In [9]:
np.array([1,2,3]) #yeni liste oluşturur


array([1, 2, 3])

In [4]:
dizi=np.array([3,4,5,6]) #yeni listeyi diziye aktarıyor
dizi

array([3, 4, 5, 6])

In [11]:
np.array([3,4,5,6,7])

array([3, 4, 5, 6, 7])

In [12]:
dizi=np.array([1,2,3,3.14],dtype=int)#dtype ile hangi değişken olduğunu öğreniriz
dizi


array([1, 2, 3, 3])

In [13]:
birboyut=np.array([1,2,3]) 
birboyut

array([1, 2, 3])

In [14]:
ikiboyut = np.array([[1,2,3], [4,5,6]])# iki boyut yapar
ikiboyut

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
ucboyut= np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])# üç boyutyapılır
ucboyut

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [16]:
np.zeros(5)# parantezin içindeki kadar 0 koyulur

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((4,3))#4 satır her satıra3 tane sıfır

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
np.ones(5)# parantezin içindeki say kadar 1 yazar

array([1., 1., 1., 1., 1.])